### ISSUE TITLE
The Chinese management api page does not load correctly

### ISSUE THREAD

**Issue by zzl221000** [casbin/casbin-website#106]
https://casbin.org/docs/zh-CN/management-api

![image](https://user-images.githubusercontent.com/14102425/86900553-0f79e000-c13e-11ea-8bdb-29734212814d.png)

**Comment by hsluoyz** [comment]
Can anyone fix it? @divy9881 @kingiw @dovics

**Comment by 00LT00** [comment]
#107

**Comment by hsluoyz** [comment]
OK. It did a blame and this bug originates from: https://github.com/casbin/casbin-website/commit/17284b51b896d8a1201b7b901aab170d991279e3#r40613246

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-website/issues/106
