### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by JAgrit20** [casbin/casbin-website#129]
the site is not responsive in many modes 
see the image the casbin name overlapping with Docs

![image](https://user-images.githubusercontent.com/65972513/92960489-5b713a00-f48b-11ea-8ad0-ecf6f3c26428.png)

**Comment by hsluoyz** [comment]
@JAgrit20 can you help fix it?

**Comment by jagrit2019** [comment]
> @JAgrit20 can you help fix it?

Yeah sure please assign this to me, 
I will be able to fix this

**Comment by JAgrit20** [comment]
yeah sure I will be able to fix it, please assign this to me

**Comment by hsluoyz** [comment]
@JAgrit20 assigned.
