### ISSUE TITLE
SpaceX is not using casbin

### ISSUE THREAD

**Issue by refs** [casbin/casbin-website#147]
Hi! Sorry for being a party pooper, but SpaceX Inc is not really using casbin. The commit linked on your site points to [github.com/r-spacex](https://github.com/r-spacex/SpaceX-API/commit/f8daa8f9878dcd7a281fc8081e3aeb8e5d216089), which is described as:

> A central location for information and collaboration on all of the awesome projects coming out of r/SpaceX

which is a subreddit. Furthermore upon reading their repo it states that they're not affiliated with SpaceX.

![image](https://user-images.githubusercontent.com/6905948/101042200-30bfea80-357d-11eb-807f-5fd33befce71.png)

Thereby I think your claim of SpaceX using Casbin is incorrect.

**Comment by hsluoyz** [comment]
Hi, it has been fixed in: https://github.com/casbin/casbin-website/commit/7ac05647b1047785e66c2e8630d8d0c174a84e88 . Thanks for the info!
