### ISSUE TITLE
Dark mode for the website

### ISSUE THREAD

**Issue by kaustubhai** [casbin/casbin-website#148]
### Feature Request
As someone who uses dark mode everywhere possible, it really sets me back to visit a website with no dark mode. Also its really in the trend now so what do you think?

**Comment by kaustubhai** [comment]
Hey @hsluoyz, can I join you on this mission?

**Comment by hsluoyz** [comment]
@kaustubhai we use Docusaurus v1 to power our website.

AFAIK, dark mode is a Docusaurus v2 only feature, see: https://v2.docusaurus.io/

But we can't easily migrate to v2 because currently v2 still lacks multi-language support, which is needed by Casbin.

So this is a big problem in front of us.

**Comment by hsluoyz** [comment]
See: https://github.com/facebook/docusaurus/issues/3317
