### ISSUE TITLE
Move this repo's CI to GitHub Actions

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#155]
Our Travis-CI ran out of quota, no builds will be run any more for now: https://travis-ci.com/github/casbin/casbin-website

![image](https://user-images.githubusercontent.com/3787410/108049475-46748480-7083-11eb-8c85-1ede8e0e1977.png)

`
Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.
`

**Comment by hsluoyz** [comment]
@closetool

**Comment by specter25** [comment]
@hsluoyz can I work on this issue ?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-website/commit/f368c511ba6aff8ab515ac2862ef1b0bb6eae224
