### ISSUE TITLE
Fix the duplicated docs bug in Crowdin translation

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#177]
I found a bug in our Crowdin translation, for a language like Chinese: https://crowdin.com/project/casbin/zh-CN#

We have two exactly the same docs for each page. The first copy is in the master folder, the other copy is in / (root) folder. I don't know why. Can any one fix this bug? It's the same for other translation languages like French, Korean.

![image](https://user-images.githubusercontent.com/3787410/110602354-e32ccc80-81c0-11eb-8d0c-0148775385ba.png)

![image](https://user-images.githubusercontent.com/3787410/110602368-e758ea00-81c0-11eb-845a-02c19e84aab2.png)

**Comment by bokket** [comment]
When I used Google Developer Tools to debug, I found that the node of the folder under the master branch and the folder under /(root) are different.It may be a static resource loading error.Maybe deleting the id="node_110" corresponding to /(root) can solve the problem.However,I am not a professional front-end developer, maybe this requires deeper debugging to modify.
![image](https://user-images.githubusercontent.com/57066972/110822279-dea10a80-82cb-11eb-88ca-cf7b18a9fe02.png)

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@hsluoyz emmm, that's my fault, when I fix ci, I set wrong path, so docs pushed to root, I thought we could just delete it.

**Comment by hsluoyz** [comment]
@closetool .. this is embarassing. Some of the docs are translated twice, lol.

Do we need to fix the CI? Even if we manually delete the folder in Crowdin, it will re-generate for next push, right?

**Comment by closetool** [comment]
@hsluoyz sorry about that, I have fixed it, now it only push docs to `/master `, so it will not re-generate

**Comment by closetool** [comment]
@hsluoyz ok
