### ISSUE TITLE
Change to table

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#183]
https://casbin.org/docs/en/rbac-96#casbin-rbac-and-rbac96

![image](https://user-images.githubusercontent.com/3787410/111027444-589bd580-842b-11eb-82f8-090e7df538f6.png)

**Comment by Vishv07** [comment]
can I work upon this enhancement issue?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-website/pull/186
