### ISSUE TITLE
Add "Data permissions" subsection to "Model"

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#187]
See: https://casbin.org/docs/en/overview#comment-5283453205

We have two solutions for data permissions (filtering):

1. https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions
2. https://casbin.org/docs/en/management-api#batchenforce

**Comment by Oyyko** [comment]
Hi. I was wondering how to add a subsection. It seems that every markdown file in the /doc starts with 
```
---
id: XXXXX
title: XXXXX
---
```
and don't include the section information.

**Comment by hsluoyz** [comment]
@Oyyko subsection is a page.

**Comment by Oyyko** [comment]
@hsluoyz  I am sorry that I did't express myself clearly. You know, there are many .md files in `/doc` and, let's say, if I add DataPermissions.md in `/doc` as a subsection, then how can the website know which section it belongs to? For example, on the website [casbin](https://casbin.org/docs/en/overview) the overview page belongs to section "The Basic". So how can I assign the new page DataPermissions.md to "Model"?

**Comment by hsluoyz** [comment]
@Oyyko see: https://github.com/casbin/casbin-website/blob/master/website/sidebars.json
