### ISSUE TITLE
Should Prisma adapter be listed in docs?

### ISSUE THREAD

**Issue by Jack-Barry** [casbin/casbin-website#195]
I don't see [prisma-adapter](https://github.com/node-casbin/prisma-adapter) listed on the [adapters page of the Casbin site](https://casbin.org/docs/en/adapters), should it be?

**Comment by hsluoyz** [comment]
@Jack-Barry added: https://github.com/casbin/casbin-website/commit/b14901679f163032c76d16cbfce46f2921b17964 thanks for reminding it!
