### ISSUE TITLE
casbin online editor can not work with "Group with domain model"

### ISSUE THREAD

**Issue by doctormacky** [casbin/casbin-website#21]
# Model

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) || g2(r.sub, p.sub, r.dom)) && r.obj == p.obj && r.act == p.act
```

#  Policy

```csv
p, admin, domain1, data1, read
g, alice, group1
g2, group1, admin, domain1
```

# Expect result:

alice, domain1, data1, read========> true

# Actual result

alice, domain1, data1, read=========> false

**Comment by hsluoyz** [comment]
Hi @doctormacky , what you see is expected. It's not online editor or Casbin's bug. ``g`` and ``g2`` are two different RBAC trees. You can't expect that you give ``alice -> group1`` in ``g`` and ``group1 -> admin`` in ``g2``, then you get ``alice -> group1 -> admin`` working. You should carefully design your matcher and check whether your matcher works for your scenario.

**Comment by hsluoyz** [comment]
Closed as resolved.
