### ISSUE TITLE
[Online Editor] Add a customized function to matchers

### ISSUE THREAD

**Issue by AliYusuf95** [casbin/casbin-website#22]
How to add [customized function](https://casbin.org/docs/en/syntax-for-models#how-to-add-a-customized-function) to matchers in the online editor?

**Comment by hsluoyz** [comment]
Hi @AliYusuf95 , we can support custom functions in online editor, but it will be Javascript, as online editor uses a front-end JS version Casbin. Is this OK for you to write custom functions in Javascript?

**Comment by AliYusuf95** [comment]
@hsluoyz yes it's fine

**Comment by nodece** [comment]
@AliYusuf95 Hey, It is [here](https://casbin.org/en/editor).
