### ISSUE TITLE
[Bug] RBAC with domain may have potential unxexpected behavior

### ISSUE THREAD

**Issue by Zxilly** [casbin/casbin-website#221]
https://github.com/casbin/casbin/blob/d8b8c3d1ad7fc2a9bf03d31955850acb1272f3e1/rbac/default-role-manager/role_manager.go#L489-L495

If we have a domain like `name::domain`, it may lead to unexpected behavior.

@closetool plz confirm this

**Comment by Zxilly** [comment]
@hsluoyz I believed this is still a potential security problem.
For example, if we have a application use casbin and allow user to define their own domain. It should be `user::customdomain` in `g`  list. 
However, the attacker can create a custom domain `admin::anotherdomain`, which result to `admin::anotherdomain::user` in `g` list. The attacker will get permission from `admin::anotherdomain`.
We can warn our user to filter `::` in domain. Or change `domainAndName` to a structure can resolve this.
Should we submit to CVE?

**Comment by hsluoyz** [comment]
@Zxilly If the user can define domain fields, then isn't he powerful enough to do anything else than just messing with the domain?

**Comment by Zxilly** [comment]
@hsluoyz like this issue https://github.com/casbin/casbin/issues/493, specially constructed organazation name can lead to  permission leakage.

**Comment by Sagilio** [comment]
@hsluoyz I think it is a potential problem too and we can avoid it with some changes.
Casbin.NET version does not have this problem. Because I use `Map<domainName, Map<roleName, role>>` structure like before and cached all roles and all domains list for pattern feature, it need not `domainAndName`.

**Comment by rrasulzade** [comment]
@hsluoyz, here documentation says we can use `::` as a separator to distinguish role from user. I'm using the same separator for domains as well. Given the concern above, do I need to update my whole database to replace the separator with a different one? Thanks
https://github.com/casbin/casbin-website/blob/master/docs/RBAC.md#how-to-distinguish-role-from-user

**Comment by Zxilly** [comment]
@rrasulzade Which language of casbin do you use?

**Comment by rrasulzade** [comment]
Go

**Comment by Zxilly** [comment]
@closetool plz notice this
