### ISSUE TITLE
Add "Matcher special grammar" section to docs

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#231]
Take the "in" operator in matcher grammar for example, it has different levels of supports for different languages: https://github.com/casbin/casbin-website/pull/206/files but adding a line to that table is not enough.

We should have a docs page especially for it.

**Comment by closetool** [comment]
@hsluoyz Is it ok to add doc at https://casbin.org/docs/en/syntax-for-models#matchers?

**Comment by hsluoyz** [comment]
@closetool it sounds OK to me.
