### ISSUE TITLE
footer links hover

### ISSUE THREAD

**Issue by oneknucklehead** [casbin/casbin-website#233]
The links in the footer section are hovered upon even when the cursor is not directly upon the link.
https://user-images.githubusercontent.com/75200954/121310673-3da10a80-c921-11eb-87ab-6f40d53d8b5c.mp4

**Comment by hsluoyz** [comment]
@oneknucklehead I think this is how Docusaurus v1 is designed: https://v1.docusaurus.io/

Actually we are migrating to v2, in which this issue has gone: https://docusaurus.io/
