### ISSUE TITLE
Change github link to github logo in nav bar

### ISSUE THREAD

**Issue by oneknucklehead** [casbin/casbin-website#234]
the link which redirects the user to the github repo in the nav bar is an anchor tag which makes it look unattractive.
This link can be changed to a hoverable github logo which does the same action.

**Comment by themonikanayak** [comment]
> the link which redirects the user to the github repo in the nav bar is an anchor tag which makes it look unattractive.
> This link can be changed to a hoverable github logo which does the same action.

Hello. I came cross your issue and I was wondering if I can do this? Thank you.

**Comment by hsluoyz** [comment]
@oneknucklehead we use Docusaurus to offer the docs. I don't know if there's a Docusaurus way to fix this?

**Comment by ErikQQY** [comment]
There are hoverable GitHub logo in [Docusaurus v2 official website](https://docusaurus.io/)

![v2](https://user-images.githubusercontent.com/52615090/122500186-e5ef5700-d024-11eb-9a93-a7506ceaeeba.png)

**Comment by hsluoyz** [comment]
@ErikQQY great! Then upgrading to v2 will fix this issue. This is WIP: https://github.com/casbin/casbin-website/pull/210

Closed for now.
