### ISSUE TITLE
The Chinese translation of Middle Wares doesn’t show properly.

### ISSUE THREAD

**Issue by ErikQQY** [casbin/casbin-website#242]
https://casbin.org/docs/zh-CN/middlewares
The Golang tab does’t show properly, while the other translations are working well.

**Comment by hsluoyz** [comment]
@ErikQQY usually it's a Crowdin translation issue. Plz fix it.

**Comment by ErikQQY** [comment]
The Golang Chinese translation for middlewares is working now:

https://casbin.org/docs/zh-CN/middlewares

**Comment by hsluoyz** [comment]
Great, thanks!
