### ISSUE TITLE
Add the C++ result to our benchmark page (between Go and Lua tabs)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#255]
See: https://github.com/casbin/casbin-cpp/pull/118#issuecomment-879064593

**Comment by hsluoyz** [comment]
@EmperorYP7

**Comment by EmperorYP7** [comment]
On it

**Comment by sagilio** [comment]
@EmperorYP7 
This looks like the test result of `CachedEnforcer`. But I think what users need is results that are not cached, can you add the result without cache here?
Why not use the result of Github Actions?
![image](https://user-images.githubusercontent.com/42855245/126046336-a1a2ee48-0541-4151-8dae-b3873c59ae4a.png)

**Comment by EmperorYP7** [comment]
@sagilio Thanks for pointing it out! Apparently, PR casbin/casbin-cpp#120 is on standby which adds the relevant benchmarks to the project. Once we merge this into master I’ll update it accordingly.

**Comment by EmperorYP7** [comment]
> Why not use the result of Github Actions?

I did this on purpose because GitHub Actions benchmarking results were inconsistent by up to 10-15% of variation across several runs. I think this is why GH Actions benchmark results for [casbin/casbin](https://github.com/casbin/casbin) and [casbin/lua-casbin](https://github.com/casbin/lua-casbin) wasn't used as well. However, the results on my hardware were very consistent.

**Comment by hsluoyz** [comment]
@EmperorYP7 merged: https://github.com/casbin/casbin-cpp/pull/120

**Comment by sagilio** [comment]
> > Why not use the result of Github Actions?
> 
> I did this on purpose because GitHub Actions benchmarking results were inconsistent by up to 10-15% of the variation across several runs. I think this is why GH Actions benchmark results for [casbin/casbin](https://github.com/casbin/casbin) and [casbin/lua-casbin](https://github.com/casbin/lua-casbin) wasn't used as well. However, the results on my hardware were very consistent.

You are right, there are indeed deviations in the environment of Github Actions, but I think it might be closer to the server environment than Apple M1.
@hsluoyz This is just a suggestion, can we find a server that has popular computing power, let multiple languages versions run on it separately and output have comparative value and actual reference value results?

**Comment by EmperorYP7** [comment]
> I think it might be closer to the server environment than Apple M1.

@sagilio Agreed. We should benchmark on a similar/same testbed which is the most popular for the use case across all versions of casbin.

**Comment by EmperorYP7** [comment]
@hsluoyz I think we should wait for a while until I find out what's wrong with the benchmark results of casbin-cpp.

Reference: [casbin/casbin-cpp#120(comment)](https://github.com/casbin/casbin-cpp/pull/120#issuecomment-882032499)
