### ISSUE TITLE
Example Model "RBAC with deny-override" in Casbin Editor Displays Error Message

### ISSUE THREAD

**Issue by itsbentsai** [casbin/casbin-website#26]

**Comment by hsluoyz** [comment]
Can you give an example?

**Comment by hsluoyz** [comment]
Hi @itsbentsai , I have tried it with no error:

![image](https://user-images.githubusercontent.com/3787410/61878832-5ddda100-af24-11e9-8fa8-f0f0e6d1883f.png)

**Comment by nodece** [comment]
@itsbentsai @hsluoyz Thanks for the report. Fixed in: d3abed5.
