### ISSUE TITLE
typo in Chinese doc

### ISSUE THREAD

**Issue by hzliangbin** [casbin/casbin-website#281]
a typo in [Chinese Documentation](https://casbin.org/docs/zh-CN/function)  

https://github.com/casbin/casbin/blob/master/util/buildtin_operators_test.go

should be

https://github.com/casbin/casbin/blob/master/util/builtin_operators_test.go

**Comment by ErikQQY** [comment]
@hzliangbin Thanks a lot! There are some problems with our Chinese docs, but we will fix it as soon as possible.

**Comment by hsluoyz** [comment]
@ErikQQY plz make a PR to fix it
