### ISSUE TITLE
[frontend]  casbinjs.Authorizer is not a constructor 

### ISSUE THREAD

**Issue by cdz620** [casbin/casbin-website#292]
I use casbin.js in my frontend project. 

I follow the docs: https://casbin.org/docs/en/frontend#advanced-usage. It occur error when I initialize casbinjs.Authorizer. 
code:
```
    const authorizer = new casbinjs.Authorizer(
        'auto', // mode
        { 'http_address' }
    );
```
error:
```
Uncaught TypeError: casbinjs.Authorizer is not a constructor
```

**Comment by hsluoyz** [comment]
@Zxilly @nodece @Abingcbc @seriouszyx can anyone improve this part of the docs?

**Comment by Zxilly** [comment]
@hsluoyz It seems that document need to be totoally rewritten.

**Comment by hsluoyz** [comment]
@Zxilly can you do this?

**Comment by Zxilly** [comment]
@hsluoyz As originally designed, casbin.js should be able to share documentation with node-casbin, but the migration of node-casbin is not yet complete.
I will complete the migration before writing the documentation.

**Comment by hsluoyz** [comment]
@cdz620 add to docs: https://github.com/casbin/casbin-website/commit/b9baded48bcb32e98aa2a3c0158bb9bddd39b571
