### ISSUE TITLE
Add Node.js examples for Mgmt API and RBAC API

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#294]
1. Mgmt API: https://casbin.org/docs/en/management-api
2. RBAC API: https://casbin.org/docs/en/rbac-api

![image](https://user-images.githubusercontent.com/3787410/145799534-c03c19fe-8f66-4f8a-b4b1-3e93f9948ba7.png)

**Comment by hsluoyz** [comment]
@fabian4 @foxzero-007 can anyone work on this?

**Comment by Shivansh-yadav13** [comment]
@hsluoyz, can I contribute?

**Comment by Shivansh-yadav13** [comment]
@hsluoyz ,There are a few more like **AddRolesForUser**, **Enforce**, **UpdatePolicy**, **LoadFilteredPolicy** missing for node example.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 then add them too
