### ISSUE TITLE
Updating Docs

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/casbin-website#306]
- [x] Missing go example for [AddRolesForUser()](https://casbin.org/docs/en/rbac-api#addrolesforuser)
- [x] Add `AddFunctionMethod()` example for Node.js
- [x] `in` of matcher is present in Node.js (https://casbin.org/docs/en/overview#docsNav)

**Comment by harshlancer** [comment]
Hey can I help in this issue?

**Comment by Shivansh-yadav13** [comment]
@harshlancer hello, I guess you are free to make a PR 😊

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 are these done already?

**Comment by Shivansh-yadav13** [comment]
yes 👍
