### ISSUE TITLE
CI error: fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#323]
See: https://github.com/casbin/casbin-website/runs/6170583331?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/165450598-7e456e2a-9180-4cd3-8f0a-a4512a03ad54.png)

**Comment by hsluoyz** [comment]
@tangyang9464 can you help take a look?

**Comment by hsluoyz** [comment]
@tangyang9464 still failed: https://github.com/casbin/casbin-website/runs/6189758244?check_suite_focus=true

**Comment by tangyang9464** [comment]
> @tangyang9464 still failed: https://github.com/casbin/casbin-website/runs/6189758244?check_suite_focus=true
My hands are tied.

**Comment by tangyang9464** [comment]
> @tangyang9464 still failed: https://github.com/casbin/casbin-website/runs/6189758244?check_suite_focus=true

solved: #325
