### ISSUE TITLE
Most of the words in the index page cannot be translated

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#331]
See a non-English language like: https://casbin.org/zh-CN/

Most of the parts are still English. They should be translatable by Crowdin.

![image](https://user-images.githubusercontent.com/3787410/166476771-c933c364-d028-43a6-bcc4-0edd2849eb8d.png)

**Comment by Selflocking** [comment]
I have opened a PR to fix it, but it's not perfect.
1. I add `<translate>` to make page can be translated, but some pages failed. 
   - [Index Page](https://casbin.org/zh-CN/) tagline, it's in `siteConfig.js`,    `An authorization library that supports ...`
   - [Help Page](https://casbin.org/zh-CN/help), they contain links, there seems to be no good solution.
2. Does the bottom of the page need to be translated?

**Comment by hsluoyz** [comment]
@Selflocking good work!

> [Index Page](https://casbin.org/zh-CN/) tagline, it's in siteConfig.js, An authorization library that supports ...

We need to find a way to translate `siteConfig.js` elements

> [Help Page](https://casbin.org/zh-CN/help), they contain links, there seems to be no good solution.

I think the <translation> tag can contain links? We usually have a lot of links in docs: https://casbin.org/docs/en/overview

> Does the bottom of the page need to be translated?

Yes

**Comment by Selflocking** [comment]
I didn't find a way to make Footer can be translated. Seem like upgrading to Docusaurus v2 can fix it.
