### ISSUE TITLE
Define all policy effect functions

### ISSUE THREAD

**Issue by QuLogic** [casbin/casbin-website#35]
[Matchers](https://casbin.org/docs/en/syntax-for-models#matchers) has a nice [table](https://casbin.org/docs/en/function) that describes all (I assume) functions that possible, but [policy effect](https://casbin.org/docs/en/syntax-for-models#policy-effect) does not. It has a bunch of examples, but no explicit explanation of anything used.

* `some` and `where` are used in examples together, but never defined individually.
* `any` is mentioned after the second inverted example, but then said to be used for "all". This is either confusingly written, or incorrect. And then what's the difference between `any` and `some`?
* `priority` is only used in the Priority example, but never defined anywhere.
* `deny` is used as a standalone variable in the Priority example, but not defined. Since policy effect is supposed to define whether a request is accepted, is `deny` just an alias for `false`?

**Comment by hsluoyz** [comment]
Can you add the table by sending a PR?

**Comment by QuLogic** [comment]
Unfortunately, I don't know the answers to these questions.

**Comment by hsluoyz** [comment]
I have added it here: https://casbin.org/docs/en/syntax-for-models
