### ISSUE TITLE
Pasting can't trigger the searching function

### ISSUE THREAD

**Issue by JalinWang** [casbin/casbin-website#352]
Keyword for testing: `getAllRolesInDomain`

Pasting text into the searching box won't get any response, even after pressing `enter` key,
![K4MH 4G ~TJNCA1$KHWCHJG](https://user-images.githubusercontent.com/20621784/175500591-b5f47225-a8d5-4936-8a2a-a07dc1d4ef01.png)

In the meantime, typing works well.
![QCSR_UUJ%~H~~{{KGKJ$9JF](https://user-images.githubusercontent.com/20621784/175500620-8bf4fc72-6561-4820-a58d-e47fc8c8d690.png)

**Comment by JalinWang** [comment]
Furthur investment: This is because no doc is related to `getAllRolesInDomain`.

Is it better to add an empty searching result popup instead of doing nothing?

**Comment by hsluoyz** [comment]
@Selflocking @EmperorYP7 @leo220yuyaodog

**Comment by JalinWang** [comment]
already upgraded to v2 https://github.com/casbin/casbin-website-v2/issues/66
