### ISSUE TITLE
Lack doc for `UpdateFilteredPolicies`

### ISSUE THREAD

**Issue by JalinWang** [casbin/casbin-website#355]
There is no doc for `Enforcer.UpdateFilteredPolicies`.
![image](https://user-images.githubusercontent.com/20621784/175822120-ffeba363-b3d2-42be-b2b8-dcfe991b0d61.png)

![image](https://user-images.githubusercontent.com/20621784/175822136-4404c275-9343-4ff3-b5b8-974163f9e116.png)

**Comment by hsluoyz** [comment]
@JalinWang can you check the v2 site?

**Comment by JalinWang** [comment]
> @JalinWang can you check the v2 site?

Nope.
![image](https://user-images.githubusercontent.com/20621784/181446076-a53e8bf7-878f-4196-a5a0-815a0c514c39.png)

I'll fix it later.
