### ISSUE TITLE
Address how Casbin implements RBAC96, including RBAC0, RBAC1, RBAC2, RBAC3

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#4]
Some users will want to know what's the relationship between Casbin' RBAC to the classic RBAC96 models. Need to clarify it.

**Comment by adrijshikhar** [comment]
@hsluoyz i would like to work on this issue, can you elaborate a bit?

**Comment by hsluoyz** [comment]
Based on academia's definition, there are four models in RBAC96: RBAC0, RBAC1, RBAC2, RBAC3.

See details at: https://security.stackexchange.com/questions/169875/rbac0-rbac1-rbac2-rbac3-what-do-they-mean

Some Casbin users are security experts and they want to know what level of RBAC (0, 1, 2, or 3) does Casbin support. So we should clarify it in the docs.

**Comment by hsluoyz** [comment]
Can anyone work on this? @nodece @GopherJ @DivyPatel9881

**Comment by DivyPatel9881** [comment]
Yes, I will have to research a bit, and then I will be updating the docs

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by Kininaru** [comment]
@hsluoyz 

Got that, working on this.
