### ISSUE TITLE
Casbin editor does not indicate whitespace errors

### ISSUE THREAD

**Issue by somahargitai** [casbin/casbin-website#41]
Casbin editor (just like Casbin) won't have a _true_ response, if the policy spacing is done with tabs.

Example request: 
  myuserid, /someurl, GET

This policy will have a _false_ response:
  p, user, /someurl, **TAB HERE** GET
  g, myuserid, user

This policy will have a _true_ response:
  p, user, /someurl, **SPACE HERE** GET
  g, myuserid, user

As there is a Syntax Validate button in the editor, I recommend you to provide a syntax warning for this validation if there is any wrong whitespacing in the policy.

**Comment by hsluoyz** [comment]
@nodece can we do this?

**Comment by nodece** [comment]
@hsluoyz Yes, I know what to do.

**Comment by nodece** [comment]
@somahargitai Thank you for your report! It is working.

**Comment by somahargitai** [comment]
Thanks, guys
