### ISSUE TITLE
RBAC addRoleForUser response 

### ISSUE THREAD

**Issue by somahargitai** [casbin/casbin-website#44]
docs says:
> AddRoleForUser adds a role for a user. Returns **false** if the user already has the role (aka not affected).

In spite of that, in 'already exists' case the response is the same we get when having a successful adding: the role list of the user

https://casbin.org/docs/en/rbac-api

**Comment by hsluoyz** [comment]
If you believe a Casbin implementation has a different behavior than the docs, please fire a bug report in that implementation's GitHub repo issues page.

**Comment by hsluoyz** [comment]
Closed as stale.
