### ISSUE TITLE
collapsing of content 

### ISSUE THREAD

**Issue by coderbabu10** [casbin/casbin-website#50]
**As try dashboard should have some space between the other components**

**Screenshot:**
![Screenshot from 2020-02-21 11-51-12](https://user-images.githubusercontent.com/54955755/75009454-bb2cd700-54a0-11ea-9814-1ac708724185.png)

**Additional Context:**
If this really is a bug, I would like to take this up.

**Comment by nodece** [comment]
hi guys, welcome PR!

**Comment by romitkarmakar** [comment]
Resolved this issue in PR #53
