### ISSUE TITLE
Add docs for new scaling ABAC feature

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#78]
For: https://github.com/casbin/casbin/issues/354

Add to this page: https://casbin.org/docs/en/abac

**Comment by hsluoyz** [comment]
@nodece @GopherJ @DivyPatel9881 can anyone work on this?

**Comment by DivyPatel9881** [comment]
I can take this issue if everyone is okay with it?

**Comment by dre-sctg** [comment]
The documentation is a bit unclear, or I'm missing something, I can't get this example running in the editor. 

```model.conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```
```policy.csv
p, r.sub.Age > 18, /data1, read
p, r.sub.Age < 60, /data2, write
```
```
{ Age: 30}, /data1, read
```
evaluates to `false` which is confusing. I'd say that is doing a string comparison, but I think an adding an explicit example of a request in the doc will be helpful.

**Comment by hsluoyz** [comment]
Hi @dre-sctg , the online editor repo is: https://github.com/casbin/casbin-editor It uses Node-Casbin, which already has the "scaling ABAC" feature: https://github.com/casbin/node-casbin/pull/151

But it seems we didn't update casbin-editor's dependency to latest Node-Casbin yet, @nodece @kingiw @zhmushan can anyone help on this?

**Comment by zhmushan** [comment]
@hsluoyz I just changed the version number in the `package.json`, is this enough?

**Comment by hsluoyz** [comment]
@zhmushan I don't know. Can you run a local casbin editor and test if @dre-sctg 's model & policy works?

**Comment by zhmushan** [comment]
I changed a little to support abac.

**Comment by hsluoyz** [comment]
Is it working now?

**Comment by zhmushan** [comment]
@hsluoyz yes.

**Comment by hsluoyz** [comment]
@zhmushan but I tried and it's still false. Can you troubleshoot it?

![image](https://user-images.githubusercontent.com/3787410/83935118-f00f3080-a7e8-11ea-8e6c-876010b04521.png)

**Comment by zhmushan** [comment]
@hsluoyz I'm sure it works when the model is abac, I will check it later.

**Comment by zhmushan** [comment]
I think the current behavior is as expected, only when `modelKind === 'abac'`, the result will be evaluated correctly. see: https://github.com/casbin/casbin-editor/blob/master/src/editor/run-test.tsx#L104

**Comment by dre-sctg** [comment]
Thanks, I can confirm the example works when the model dropdown is set to `abac`. Is there anything I can do to help? Perhaps update the docs with an example and a comment?

**Comment by dre-sctg** [comment]
I am afraid this update has caused another issue, running the plain ABAC example now shows `Invalid policy, policy document cannot be false-y` as error message. I'll create an issue in the editor repository, and submit a PR if thats ok.
