### ISSUE TITLE
Improve the "Open Chat" button on website

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#81]
As a continue of previous PR: https://github.com/casbin/casbin-website/issues/80

1. The color of the "Open Chat" button should be changed to our "blue" color.

![image](https://user-images.githubusercontent.com/3787410/80986203-d5047600-8e62-11ea-8690-7f3f6f2c6f5e.png)

2. The close button is overlapped by top bar:

![image](https://user-images.githubusercontent.com/3787410/80986392-172db780-8e63-11ea-8684-90557431fd04.png)

See the official example: https://sidecar.gitter.im/

![image](https://user-images.githubusercontent.com/3787410/80986508-3cbac100-8e63-11ea-988d-00f7cda20b87.png)

**Comment by hsluoyz** [comment]
Can anyone work on this? @nodece @GopherJ @DivyPatel9881

**Comment by DivyPatel9881** [comment]
Yeah, I can work on this.
