### ISSUE TITLE
Add docs for the "Explain enforcement" feature

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#82]
Issue: https://github.com/casbin/casbin/issues/355
PR: https://github.com/casbin/casbin/pull/425

**Comment by hsluoyz** [comment]
@nodece @GopherJ @hackerchai @DivyPatel9881 @kingiw can anyone work on it?

**Comment by Kininaru** [comment]
We already have documentation on this: [API tutorial](https://casbin.org/docs/en/api-tutorial) and [Management API](https://casbin.org/docs/en/management-api). Are these docs clear enough? Or should I add instructions of this feature in a special page?

**Comment by Kininaru** [comment]
Got it. Working on this.
