### ISSUE TITLE
Heading should be at the centre of the screen

### ISSUE THREAD

**Issue by samagragupta** [casbin/casbin-website#87]
![Capture](https://user-images.githubusercontent.com/32234926/82022205-e1ca6a80-96a9-11ea-9885-bf1cddc4cc6c.JPG)
In mobile view: Heading should be at the centre of the screen

**Comment by chetan-v** [comment]
@samagragupta I done it,
by change the text-align: center in main.css

**Comment by samagragupta** [comment]
@chetan-v I could not see your Pull request.
