### ISSUE TITLE
Problem in bot(Mobile interface). There is no icon for close the bot

### ISSUE THREAD

**Issue by chetan-v** [casbin/casbin-website#92]
![Screenshot_20200519-144025 (1)](https://user-images.githubusercontent.com/63091769/82308574-98e32080-99df-11ea-8c6a-e173195e7cbd.png)
![Screenshot_20200519-144037](https://user-images.githubusercontent.com/63091769/82308597-9ed90180-99df-11ea-9dc5-4ef135db348e.png)

**Comment by hsluoyz** [comment]
@nodece @GopherJ @DivyPatel9881 @kingiw @hackerchai can anyone fix it?

**Comment by chetan-v** [comment]
@hsluoyz  I do something for this

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-website/pull/93
