### ISSUE TITLE
Add docs for Management and RBAC Batch API.

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#94]
Currently, we added batch API to some languages already:

Go: https://github.com/casbin/casbin/issues/386
Node.js: https://github.com/casbin/node-casbin/issues/105

But we don't have docs. Can anyone work on a new "Batch API" page? @nodece @GopherJ @DivyPatel9881 @kingiw @hackerchai

**Comment by DivyPatel9881** [comment]
I will work on this.
